-- Cascade — Extension features (Tier 1 + Tier 2)
--
-- Additive only. 001_schema.sql is the frozen Day-0 contract and is not
-- edited; everything here is new surface, so an existing deployment can apply
-- this without a rebuild.

BEGIN;

-- ============================================================================
-- NEGATIVE MEMORY (T2.5)
-- ============================================================================
-- Only successes were ever compiled, so a failed approach was forgotten the
-- moment the task ended and the agent could rediscover the same dead end
-- forever. An anti-playbook records what was tried, on what class of incident,
-- and why it failed — and is injected into the explore prompt as a warning.
--
-- Deliberately NOT a playbook with a flag: these are never retrieved for
-- execution, only for avoidance, and conflating the two risks running one.
CREATE TABLE IF NOT EXISTS anti_playbooks (
    anti_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    incident_kind VARCHAR(50) NOT NULL,
    attempted_action VARCHAR(50),
    failure_reason TEXT NOT NULL,
    trajectory_digest JSONB NOT NULL DEFAULT '{}',
    episode_id UUID REFERENCES episodes(episode_id) ON DELETE SET NULL,
    occurrences INT NOT NULL DEFAULT 1,
    embedding VECTOR(1024),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (occurrences > 0)
);

CREATE INDEX IF NOT EXISTS anti_kind_idx ON anti_playbooks (incident_kind, updated_at DESC);
CREATE INDEX IF NOT EXISTS anti_action_idx ON anti_playbooks (incident_kind, attempted_action);

-- ============================================================================
-- APPROVALS (T1.1) — additive columns on the Day-0 table
-- ============================================================================
-- The Day-0 table has no way to resume: an approved step needs to know which
-- arguments were pending and which playbook context to resume into.
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS tool_name VARCHAR(50);
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS tool_args JSONB NOT NULL DEFAULT '{}';
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS risk VARCHAR(10) NOT NULL DEFAULT 'high';
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS incident_id VARCHAR(20);

-- ============================================================================
-- INSIGHTS (T1.2) — additive
-- ============================================================================
-- Insights are regenerated by a periodic scan; without a stable key each run
-- would duplicate every finding. This is the idempotency key for that scan.
ALTER TABLE insights ADD COLUMN IF NOT EXISTS fingerprint VARCHAR(120);
ALTER TABLE insights ADD COLUMN IF NOT EXISTS applied BOOLEAN NOT NULL DEFAULT FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS insights_fingerprint_idx
    ON insights (fingerprint) WHERE fingerprint IS NOT NULL;

-- ============================================================================
-- POSTMORTEMS (T1.3) — additive
-- ============================================================================
-- s3_key is NOT NULL in the Day-0 schema, but with no bucket configured there
-- is nothing to point at. The body is stored inline so the feature works
-- without S3, and s3_key is populated when a bucket exists.
ALTER TABLE postmortems ADD COLUMN IF NOT EXISTS body TEXT;
ALTER TABLE postmortems ALTER COLUMN s3_key DROP NOT NULL;

-- ============================================================================
-- OUTBOX — widen the job vocabulary
-- ============================================================================
-- The Day-0 CHECK allows compile / rule_changed / relearn / recheck_suspect /
-- postmortem. Tier 1-2 add two more job kinds, and a CHECK cannot be extended
-- in place, so it is replaced.
-- CockroachDB names an inline column CHECK `check_<column>`.
ALTER TABLE outbox DROP CONSTRAINT IF EXISTS check_kind;
ALTER TABLE outbox DROP CONSTRAINT IF EXISTS outbox_kind_check;

ALTER TABLE outbox ADD CONSTRAINT outbox_kind_check CHECK (
    kind IN (
        'compile', 'rule_changed', 'relearn', 'recheck_suspect',
        'postmortem', 'insight_scan', 'triage'
    )
);

COMMIT;

-- ============================================================================
-- Vector index for negative memory — outside the transaction (backfill job)
-- ============================================================================
SET CLUSTER SETTING feature.vector_index.enabled = true;

CREATE VECTOR INDEX IF NOT EXISTS anti_embed_idx ON anti_playbooks (embedding);
